#!/bin/sh

# Taken and modified from: https://github.com/ericmurphyxyz/dotfiles/blob/master/.local/bin/changevolume

# Increment, decrement, or mute the volume and send a notification of the current volume level.

send_notification() {
	volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | tr -dc "0-9" | sed 's/^0\{1,2\}//')
	dunstify -a "changevolume" \
		-u low \
		-r 9993 \
		-h int:value:"$volume" \
		-i "${XDG_CONFIG_HOME}/dunst/icons/volume-$1.png" \
		"Volume: ${volume}%" \
		-t 3000 
}

case $1 in
up)
	# Set the volume on (if it was muted)
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+
	send_notification "$1"
	;;
down)
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-
	send_notification "$1"
	;;
mute)
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
	if [ "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -oE "[A-U]+")" = "MUTED" ]; then
		dunstify -a "changevolume" -t 2000 -r 9993 -u low -i "${XDG_CONFIG_HOME}/dunst/icons/volume-mute.png" "Volume Muted"
	else
		send_notification up
	fi
	;;
esac
