#!/bin/sh

# This is a scratchpad script that works for both TUI and GUI applications. 

case "$1" in
	terminal)
		entry="$TERMINAL --class terminal" ;;

	fm)
		entry="$TERMINAL --class fm -e ranger" ;;

	music)
		entry="$TERMINAL --class music -e cmus" ;;

	bluetooth)
		entry="$TERMINAL --class bluetooth -e bluetuith" ;;
	
	email)
		entry="$TERMINAL --class email -e neomutt" ;;

	tageditor)
		entry="easytag" ;;

	whiteboard)
		entry="xournalpp" ;;
esac

case "$entry" in
	easytag)
		xdotool search --onlyvisible --name "EasyTAG" windowunmap \
			|| xdotool search --name "EasyTAG" windowmap || $entry &
					;;
	xournalpp)
		xdotool search --onlyvisible --classname "com.github.xournalpp.xournalpp" windowunmap \
			|| xdotool search --classname "com.github.xournalpp.xournalpp" windowmap || $entry &
					;;
	*)
		xdotool search --onlyvisible --classname "$1" windowunmap \
			|| xdotool search --classname "$1" windowmap || $entry &
					;;
esac
