#!/bin/sh

# Taken and modified from: https://gitlab.com/ceda_ei/kaomoji-rofi

current_wid=$(xdo id)
selection=$(dmenu -x 6 -y 5 -z 1908 -h 44 -l 10 -p "Select a kaomoji:" "$@" < ~/.config/kaomoji/kaomoji.txt)
kaomoji=$(echo "${selection}" | sed "s|$(printf "\ufeff").*||")
echo -n "${kaomoji}" | xclip -selection clipboard
xdotool key --window "${current_wid}" --clearmodifiers ctrl+v
