#!/bin/sh

# A script to copy special Spanish characters to the clipboard and paste them. Useful for when you want to type in proper Español.

current_wid=$(xdo id)
selection=$(dmenu -x 6 -y 5 -z 1908 -h 44 -l 10 -p "Select a Spanish character:" "$@" < ~/.scripts/dmenu/spanish.txt)
spanish=$(echo "${selection}" | cut -d " " -f1)
echo -n "${spanish}" | xclip -selection clipboard
xdotool key --window "${current_wid}" --clearmodifiers ctrl+v
